name: Deploy Azure AI Foundry Prompt Flow

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - main  # Adjust to your default branch
permissions:
  id-token: write  # This is the important line to add
  contents: read
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Set Up Python Environment
        uses: actions/setup-python@v5.5
        with:
          python-version: '3.8'  # Specify the required Python version

      #- name: Install Dependencies
      #  run: |
      #    python -m pip install --upgrade pip
      #    pip install -r requirements.txt
      
      - name: Install Prompt Flow CLI
        run: |
          pip install promptflow  # Install the Prompt Flow CLI

      - name: Azure Login with OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      #- name: Install Azure ML CLI Extension
      #  run: |
      #    az extension add -n ml -y

      - name: Deploy Prompt Flow
        run: |
          pfazure flow create --source . --name test --workspace ${{ secrets.AZURE_ML_WORKSPACE }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }}
      #- name: Deploy Prompt Flow
      #  run: |
      #    az ml online-endpoint create --name my-promptflow-endpoint --file flow.dag.yaml --workspace-name ${{ secrets.AZURE_ML_WORKSPACE }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }}
        env:
          AZURE_ML_WORKSPACE: ${{ secrets.AZURE_ML_WORKSPACE }}
          AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
